### ISSUE TITLE
Links don't work!

### ISSUE THREAD

**Issue by salmamzfr** [BlockResearchGroup/compas_3gs#3]
Could you please update the links below this page: 
https://blockresearchgroup.github.io/compas_3gs/01_getting_started.html

I am specifically looking  for examples:
https://compas-dev.github.io/compas_3gs/examples.html

**Comment by juney-lee** [comment]
Thanks for pointing this out! The links indeed are outdated (old compas-dev links). Those examples are referring to the items under "user manual", which you can still access:
[https://blockresearchgroup.github.io/compas_3gs/04_user_manual.html](url) 

I will fix/update the links.
